events { 
    worker_connections 1024; 
}

http {
    upstream rust_backend {
        server api:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://rust_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}